version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: my_container_db
    environment:
      - POSTGRES_DB=mystore
      - POSTGRES_USER=platzi
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
